argo

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -1,93 +1,93 @@
-name: ci
+# name: ci
 
-on:
-  push:
-    branches:
-      - "main"
+# on:
+#   push:
+#     branches:
+#       - "main"
 
-env:
-  TEST_TAG: rumrum/minesweeper:test
-  LATEST_TAG: rumrum/minesweeper:latest
-  PATH_TAG: rumrum/minesweeper
-  COMMIT_HASH: ${{ github.sha }}
+# env:
+#   TEST_TAG: rumrum/minesweeper:test
+#   LATEST_TAG: rumrum/minesweeper:latest
+#   PATH_TAG: rumrum/minesweeper
+#   COMMIT_HASH: ${{ github.sha }}
 
-jobs:
-  docker:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
-      - name: Login to Docker Hub
-        uses: docker/login-action@v3
-        with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
+# jobs:
+#   docker:
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: Checkout
+#         uses: actions/checkout@v4
+#       - name: Set up Docker Buildx
+#         uses: docker/setup-buildx-action@v3
+#       - name: Login to Docker Hub
+#         uses: docker/login-action@v3
+#         with:
+#           username: ${{ secrets.DOCKERHUB_USERNAME }}
+#           password: ${{ secrets.DOCKERHUB_TOKEN }}
 
-      - name: Build and export to Docker
-        uses: docker/build-push-action@v5
-        with:
-          context: back
-          load: true
-          tags: ${{ env.TEST_TAG }}
+#       - name: Build and export to Docker
+#         uses: docker/build-push-action@v5
+#         with:
+#           context: back
+#           load: true
+#           tags: ${{ env.TEST_TAG }}
 
-      - name: Test
-        run: |
-          docker run -d -p 8080:8080 ${{ env.TEST_TAG }}
-          sleep 5
-          nc -zv 127.0.0.1 8080
+#       - name: Test
+#         run: |
+#           docker run -d -p 8080:8080 ${{ env.TEST_TAG }}
+#           sleep 5
+#           nc -zv 127.0.0.1 8080
 
-      - name: Stop and Clean Up
-        run: |
-          docker stop $(docker ps -q)
-          docker rm $(docker ps -aq)
+#       - name: Stop and Clean Up
+#         run: |
+#           docker stop $(docker ps -q)
+#           docker rm $(docker ps -aq)
 
-      - name: Build Docker image
-        run: |
-          cd back
-          docker build -t ${{ env.PATH_TAG }}:${{ env.COMMIT_HASH }} .
-          docker push ${{ env.PATH_TAG }}:${{ env.COMMIT_HASH }}
-        env:
-          DOCKER_BUILDKIT: 1
+#       - name: Build Docker image
+#         run: |
+#           cd back
+#           docker build -t ${{ env.PATH_TAG }}:${{ env.COMMIT_HASH }} .
+#           docker push ${{ env.PATH_TAG }}:${{ env.COMMIT_HASH }}
+#         env:
+#           DOCKER_BUILDKIT: 1
 
-      - name: Deploy new Docker image on the target server
-        run: |
-          echo "${{ secrets.SSH_PRIVATE_KEY }}" > id_rsa
-          chmod 600 id_rsa
-          ssh -o StrictHostKeyChecking=no -i id_rsa ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_SERVER_IP }} -p18022 <<EOF
-            sudo docker pull ${{ env.PATH_TAG }}:${{ env.COMMIT_HASH }}
-            sudo docker stop minesweeper && sudo docker rm minesweeper || true
-            sudo docker run -d --network jj-network --name minesweeper ${{ env.PATH_TAG }}:${{ env.COMMIT_HASH }}
-          EOF
+#       - name: Deploy new Docker image on the target server
+#         run: |
+#           echo "${{ secrets.SSH_PRIVATE_KEY }}" > id_rsa
+#           chmod 600 id_rsa
+#           ssh -o StrictHostKeyChecking=no -i id_rsa ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_SERVER_IP }} -p18022 <<EOF
+#             sudo docker pull ${{ env.PATH_TAG }}:${{ env.COMMIT_HASH }}
+#             sudo docker stop minesweeper && sudo docker rm minesweeper || true
+#             sudo docker run -d --network jj-network --name minesweeper ${{ env.PATH_TAG }}:${{ env.COMMIT_HASH }}
+#           EOF
 
-      - uses: actions/checkout@v4
-      - name: copy nginx config
-        uses: appleboy/scp-action@v0.1.7
-        with:
-          host: ${{ secrets.SSH_SERVER_IP }}
-          username: ${{ secrets.USER_NAME }}
-          key: ${{ secrets.SSH_PRIVATE_KEY }}
-          port: 18022
-          source: "nginx/ms.justmy.site.conf"
-          target: /opt/jj-nginx/conf.d
+#       - uses: actions/checkout@v4
+#       - name: copy nginx config
+#         uses: appleboy/scp-action@v0.1.7
+#         with:
+#           host: ${{ secrets.SSH_SERVER_IP }}
+#           username: ${{ secrets.USER_NAME }}
+#           key: ${{ secrets.SSH_PRIVATE_KEY }}
+#           port: 18022
+#           source: "nginx/ms.justmy.site.conf"
+#           target: /opt/jj-nginx/conf.d
 
-      - uses: actions/checkout@v4
-      - name: copy frontend
-        uses: appleboy/scp-action@v0.1.7
-        with:
-          host: ${{ secrets.SSH_SERVER_IP }}
-          username: ${{ secrets.USER_NAME }}
-          key: ${{ secrets.SSH_PRIVATE_KEY }}
-          port: 18022
-          source: "minesweeper.js,styles.css,index.html"
-          target: /opt/jj-nginx/conf.d/minesweeper
+#       - uses: actions/checkout@v4
+#       - name: copy frontend
+#         uses: appleboy/scp-action@v0.1.7
+#         with:
+#           host: ${{ secrets.SSH_SERVER_IP }}
+#           username: ${{ secrets.USER_NAME }}
+#           key: ${{ secrets.SSH_PRIVATE_KEY }}
+#           port: 18022
+#           source: "minesweeper.js,styles.css,index.html"
+#           target: /opt/jj-nginx/conf.d/minesweeper
 
-      - name: Deploy frontend
-        run: |
-          ssh -o StrictHostKeyChecking=no -i id_rsa ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_SERVER_IP }} -p18022 <<EOF
-            sudo docker exec -t jj-nginx nginx -s reload
-          EOF
+#       - name: Deploy frontend
+#         run: |
+#           ssh -o StrictHostKeyChecking=no -i id_rsa ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_SERVER_IP }} -p18022 <<EOF
+#             sudo docker exec -t jj-nginx nginx -s reload
+#           EOF
 
-      - name: cleanup
-        run: rm -rf id_rsa
+#       - name: cleanup
+#         run: rm -rf id_rsa
